name: sideswap_logger
description: Sideswap custom logger
version: 0.0.14

environment:
  sdk: ^3.12.2
  flutter: ^3.44.4

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
